var GAME_LEVELS = [
  ["                                             !!!!!!!!                           ",
   "                                                 v                              ",
   "                                                                                ",
   "                                                                          o     ",
   "                                                                     xxxxxxxx   ",
   "                                                                                ",
   "                                                         xxxxxxx                ",
   "  x                                                                             ",
   "  x                                                                             ",
   "  x                                             xxxxxx                          ",
   "  x               x  g    x                                                     ",
   "  x               xxxxxxxxx                                                 xx  ",
   "  x              xxxxxxxxxx       xxxxxxxxx                                     ",
   "  x             xxxxxxxxxxx                                                     ",
   "  x           xxxxxxxxxxxxx                                                     ",
   "  x          xxxxxxxxxxxxxx                                                     ",
   "  x  @      xxxxxxxxxxxxxxx                                                     ",
   "  xxxxxxxxxxxxxxxxxxxxxxxxxxxxx                                                 ",
   "                              x!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
   "                              x!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
   "                              x!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
   "                              xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "                                                                                ",
   "                                                                                "],
  ["x                                            !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!                     !!!!!!     ",
   "x     o                                       v        v       v        v       v                      v          ",
   "x   xxxxx                                                                                                v        ",
   "xxxxxxxxxxxxx                                                                                              v      ",
   "x                                                                                                                 ",
   "x              xxxxxxxxx                                                                 xxxxxxxxx                ",
   "x                     xxxx                                    x                         x!!!!!!!!!x               ",
   "x                           xg         gx                     x                        xx  v   v  xxxxx         xx",
   "x                           xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx   v v   xx         xxxxx",
   "x                                                                                      xx    v    xx            xx",
   "x                                                                                      xx         xx            xx",
   "x                                                                                      xx         xxxxx         xx",
   "x                                                                                      xx         xx            xx",
   "x                                                                                      xx         xx            xx",
   "x                                                                                      xx         xx         xxxxx",
   "x                                                                                      xx         xx            xx",
   "x                                                                                      xx         xx            xx",
   "x                                                                                      xx         xxxxx         xx",
   "x                                                                                      xx         xx            xx",
   "x                                                                                      xx         xx            xx",
   "x    @                                                                                 xx         xx         xxxxx",
   "x   xxx    xxx                                                                         xx         xx            xx",
   "x   xxx    xxxx                                                                        xx         xx            xx",
   "x!!!xxx!!!!xxxxx                                                                       xx         xxxxx         xx",
   "x!!!xxx!!!!xxxxxx                                                                                               xx",
   "x!!!xxx!!!!xxxxxxx               xx    xx                                                                       xx",
   "x!!!xxx!!!!xxxxxxxx             xxx    xxx                                                                   xxxxx",
   "x!!!xxx!!!!xxxxxxxxx           xxxx g  xxxx                                                                  xxxxx",
   "x!!!xxx!!!!xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx       xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx      xxxxx",
   "x!!!xxx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!"],
  ["                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                         o                                                                    ",
   "              xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx                  xxxxxxxxxxxxxxxx",
   "              x                                                                                              x",
   "              x                                                                                              x",
   "              x                                                               x  g  g  x                     x",
   "              xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx        x",
   "              !                                                                            x                 x",
   "              !                                                                            x                 x",
   "              !                                                                            x                 x",
   "              xxxxxxxxxxx       xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx        x           xxxxxxx",
   "              x                                                !                           x                 x",
   "   x           x                                               !                           x                 x",
   "                x                                              !                           x                 x",
   "                 xxxxxxxxxxxxxxxxxxxxxx           xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx    xxxxxxxxxxxxx",
   "xxxxxxxxx                                                                         x                          x",
   "xxxxxxxxx                                                                         x                          x",
   "xxxxxxxxx                                 b                                       x                          x",
   "xxxxxxxxxxxxx          xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx  xxxxxxxxxxxxxxx      xxxxxxx",
   "xxxxxxxxxxxxx                                                                x                               x",
   "                                                                             x                               x",
   "    x                                  xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx              xxxxxxxxx        x",
   "    x            x          xx                                                                               x",
   "    x     @     xxx         xx                                                                               x",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!     xxx                    x",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!x                           x",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!                           x",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!x"],
  ["                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                @                                                               ",
   "                                                                                ",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "                                                                                ",
   "      x   x   xx    x  x       x  x  x   x  x  x  x                             ",
   "       x x   x  x   x  x       x  x  x   x  xx x  x                             ",
   "        x    x  x   x  x       x  x  x   x  x xx                                ",
   "        x     xx     xx         xx xx    x  x  x  x                             ",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
   "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!"]
];

if (typeof module != "undefined" && module.exports)
  module.exports = GAME_LEVELS;
